-- Feature toggle settings for vehicles (controllable from iOS app)
ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS enable_yolo BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS enable_stream BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS enable_shazam BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS enable_microphone BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS enable_camera BOOLEAN NOT NULL DEFAULT TRUE;
